services:
  frontend:
    build: frontend
    init: true
    ports:
      - "3000:3000"

  backend:
    build: backend
    init: true
    ports:
      - "8080:8080"
      - "40000:40000" # debugger port
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - backend/.env
    environment:
      #SERVER_URL: "" # must be empty for localhost
      REDIRECT_URL: http://localhost:8080/dashboard
      PORT: 8080
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_OPTS: sslmode=disable # sslmode=require for prod

  database:
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432" # This is only used for connecting to the database during local development
    volumes:
      - bee-postgres-data:/var/lib/postgresql/data
      - ./backend/sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  backend-executor:
    build: backend-executor
    init: true
    depends_on:
      database:
        condition: service_healthy
      influxdb2:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  influxdb2:
    image: influxdb:2.7-alpine
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: beeci
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    healthcheck:
      test: ["CMD-SHELL", "influx ping"]
      interval: 2s
      timeout: 2s
      retries: 3

volumes:
  influxdb2-data:
  influxdb2-config:
  bee-postgres-data:
