services:
  frontend:
    build: frontend
    init: true
    ports:
      - "3000:3000"

  backend:
    build: backend
    init: true
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - backend/.env
    environment:
      PORT: 8080
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: bee
      DB_OPTS: sslmode=disable # sslmode=require for prod

  database:
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432" # This is only used for connecting to the database during local development
    volumes:
      - bee-postgres-data:/var/lib/postgresql/data
      - ./backend/sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

volumes:
  bee-postgres-data:
