services:
  app:
    build: .
    init: true
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: bee

  database:
    image: postgres:16.3-alpine3.20
    init: true
    ports:
      - 5432:5432
    volumes:
      - bee-postgres-data:/var/lib/postgres
      - ./sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 3
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: bee

volumes:
  bee-postgres-data:
