services:
  app:
    build: .
    init: true
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PORT: 8080
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: bee

  database:
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - bee-postgres-data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

volumes:
  bee-postgres-data:
