services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: bee

  database:
    image: postgres:16.3-alpine3.20
    volumes:
      - bee-mysql-data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bee

volumes:
  bee-mysql-data:
