app = "bee-ci"
primary_region = "ewr" # https://fly.io/docs/reference/regions/

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = 8080

  DB_HOST = "bee-ci-postgres.flycast"
  DB_PORT = 5432
  DB_USER = "postgres"
  # DB_PASSWORD is secret
  DB_NAME = "postgres"

[checks]
  [checks.name_of_your_http_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/"
    port = 8080
    timeout = "10s"
    type = "http"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
