#!/usr/bin/env sh
set -eu # -o pipefail # Debian dash does not support -o pipefail

# This script creates the .env file.

VAULT="bee-ci"

true >.env # Clear file

_export() {
	name="${1:-}"
	value="${2:-}"

	echo "$name"
	echo "$name=$value" >>.env
}

_export GITHUB_APP_ID "$(op read "op://$VAULT/GitHub App/app ID")"
_export GITHUB_APP_WEBHOOK_SECRET "$(op read "op://$VAULT/GitHub App/webhook secret")"
_export GITHUB_APP_PRIVATE_KEY_BASE64 "$(op read "op://$VAULT/GitHub App/private key/content base64")"
