name: Publish images to GHCR

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        run: |
            cd backend
            docker build -t ghcr.io/${{ github.repository }}/backend:latest -f server.dockerfile .
            docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Build and push gh-updater image
        run: |
            cd backend
            docker build -t ghcr.io/${{ github.repository }}/gh-updater:latest -f gh-updater.dockerfile .
            docker push ghcr.io/${{ github.repository }}/gh-updater:latest

      - name: Build and push executor image
        run: |
          cd executor
          docker build -t ghcr.io/${{ github.repository }}/executor:latest -f Dockerfile .
          docker push ghcr.io/${{ github.repository }}/executor:latest

      - name: Build and push frontend image
        run: |
            cd frontend
            docker build -t ghcr.io/${{ github.repository }}/frontend:latest -f Dockerfile .
            docker push ghcr.io/${{ github.repository }}/frontend:latest
