name: Publish images to GHCR

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        run: |
            cd backend
            docker build -t ghcr.io/${{ github.repository }}/backend:latest server.dockerfile
            docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Build and push gh-updater image
        run: |
            cd backend
            docker build -t ghcr.io/${{ github.repository }}/gh-updater:latest gh-updater.dockerfile
            docker push ghcr.io/${{ github.repository }}/gh-updater:latest

      - name: Build and push frontend image
        run: |
            cd frontend
            docker build -t ghcr.io/${{ github.repository }}/frontend:latest .
            docker push ghcr.io/${{ github.repository }}/frontend:latest
